### ISSUE TITLE
User can view list of action items

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/oneheartconnect#1]
![screen shot 2016-09-29 at 10 31 44 am](https://cloud.githubusercontent.com/assets/19194235/18965591/b6cca3ba-8632-11e6-8923-d5f72c3eb42e.png)

**Comment by farookkhan** [comment]
![screen shot 2016-10-03 at 4 05 33 pm](https://cloud.githubusercontent.com/assets/19194235/19057274/8f15224e-8983-11e6-8365-024be23c4309.png)

**Comment by farookisonfire** [comment]
![screen shot 2016-10-03 at 4 27 41 pm](https://cloud.githubusercontent.com/assets/19194235/19057660/5cda948c-8986-11e6-83f3-134ecee1d622.png)
